### ISSUE TITLE
What is the performance like?

### ISSUE THREAD

**Issue by willemneal** [near/near-sdk-js#1]
- How big are the binaries?
- How much gas is the overhead?

**Comment by ailisp** [comment]
The binary for a counter contract is about 530KB, almost same as the base quickjs.wasm. A more complicated contract doesn't add much, a 2000 line javascript add about 20KB.

The gas is good. For a mint_nft op, Using near-vm-runner-standalone to test it's about 2T Gas. Test it on a local node and includes the receipts, totally about 7T Gas.

**Comment by ailisp** [comment]
For future reference, we decide to move to an enclave approach: only one copy of javascript-vm.wasm is deployed and user deploy js bytecode, which is quite small. It is quite similar to EVM.
