### ISSUE TITLE
Remove need for redundant reads/writes for `UnorderedMap`

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-js#107]
Seems like the implementation was taken from the old Rust SDK algorithm. The inefficiency is that it stores a mapping of key to index, one vector for keys and one for vector.

So for every read/write, you are charging basically twice for each read/write since they are separated instead of just being one vector of key/value tuples (`<span class="error">[string, string]</span>`). This is an easy optimization but is state-breaking.

The second inefficiency is having to do two storage reads when retrieving any value because the indices are stored in a separate lookup. This is also inefficient because you do swap_removes when removing entries, and this means that two different storage reads need to be charged for this operation.

The optimized version (which may not be perfect, but what we decided to go with) is here [https://github.com/near/near-sdk-rs/blob/1a39f1e2406517ee93bc4efb0b859751297e645d/near-sdk/src/store/unordered_map/mod.rs](https://github.com/near/near-sdk-rs/blob/1a39f1e2406517ee93bc4efb0b859751297e645d/near-sdk/src/store/unordered_map/mod.rs). The `FreeList` type that is used isn't required, but removes the requirement of having to swap_remove values.

My recommendation would be to optimize this sooner than later before it starts being used in prod, or else you will be stuck with this inefficiency to avoid making state-breaking changes (like we are with the collection this algo was taken from).

**Comment by ailisp** [comment]
Got it! You're right, this is a high priority issue that we should address now

**Comment by ryancwalsh** [comment]
This does sound important. Does anyone have plans to address it in the next couple of days as NEARCON approaches? Or is it lower priority?

**Comment by ailisp** [comment]
I'll have a look today!

**Comment by petarvujovic98** [comment]
Here is a [repository](https://github.com/Learn-NEAR/NCD.L1.sample--lottery) I was working on, that is experiencing some gas issues. This is a semi-intermediate example yet the collection inefficiencies are causing gas exceeds in my tests.

At first I thought it might be Promises that were causing this but upon further debugging it seems that the `UnorderedSet` was the culprit. Although there might also be other problems.

This is also a contract which was ported from AssemblyScript to both Rust and JavaScript and only JavaScript is having these issues with gas. I think it is pretty important to address this as it means that in any complex contract the SDK might be unusable

**Comment by ailisp** [comment]
@petarvujovic98 I debugged your contract, looks like it's a different issue: the promise object need to return instead of call onReturn, and tests passed after this change:

https://github.com/ailisp/NCD.L1.sample--lottery/commit/98bf76b074a82ac6b015d6930da919e066bc54ce

**Comment by petarvujovic98** [comment]
@ailisp Thank you for fixing the contract. But makes wonder why does the promise need to be returned? If there is no way except to return it, we should have an explanation about it and let users know that they need to do that.

**Comment by ailisp** [comment]
This is mentioned in readme:
```
In a @call method, you can return either a JavaScript value or a NearPromise object. In the later case, @NearBindgen will automatically promiseReturn it for you.
```

It's not very obvious. If you have a better way to explain / wording, it would be great to send a PR!

**Comment by petarvujovic98** [comment]
This mentions what the process is. But I still don't understand _**why**_ it needs to be returned

**Comment by ailisp** [comment]
In low level, a contract function either calls value_return or promise_return. In high level, we (nearbindgen) call value_return and promise_return for you, depending on the type you return in JavaScript. So in this case you want to do a Promise, a NearPromise need to be returned. If you were return void (undefined), value_return get called and that causes problem

**Comment by petarvujovic98** [comment]
To check if my understanding is correct:
If I return a `NearPromise` through any function, doesn't have to be an exposed contract method, it will get called and everything will work.

If I just create a `NearPromise` anywhere without returning it, even if it is within a exposed contract method, it will not get called and the call will exceed gas? hang indefinitely? other problems??

**Comment by ailisp** [comment]
> To check if my understanding is correct:
If I return a NearPromise through any function, doesn't have to be an exposed contract method, it will get called and everything will work.
If I just create a NearPromise anywhere without returning it, even if it is within a exposed contract method, it will not get called

Yes

> the call will exceed gas? hang indefinitely? other problems??

The behavior is undefined. IIRC, I wrote some contract in rust sdk it also shows exceed gas that create promise but doesn't return it (promise_return, or in high level API, return `Promise` or `PromiseOrValue`), but I could be wrong, and it's hard to reason why this is the case.

**Comment by petarvujovic98** [comment]
Thank you for explaining. I will create a PR for this
