### ISSUE TITLE
Add formatting/linting to project

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-js#110]
Noticed there was no consistent formatting/linting included for this project and it will cause unnecessary merge conflicts. This should be enforced by the CI as well.

**Comment by ailisp** [comment]
We seem to have a number of open PRs, let's try to keep this issue in mind and do it at a moment with very little opens. @volovyk-s .

**Comment by petarvujovic98** [comment]
Using ESLint and Prettier should be enforced. I have created an opinionated version of a ESLint config called [eslint-config-near](https://github.com/NEAR-Edu/eslint-config-near) which could be used here. It is pretty strict, but IMO makes the code more readable and thus more maintainable. There is also a Prettier config called [prettier-config-near](https://github.com/NEARFoundation/near-prettier-config) by the NF engineering team. We could try to have consistent linting and formatting practices across our tooling

**Comment by volovyks** [comment]
@petarvujovic98 I can see that your config is more advanced, but I do not think that we need to create "new standards". I like something that is as close to default as possible. And there is definitely no reason to create 2 standards in NEAR ecosystem, let's just contribute to the existing one, if we really want to have something custom.

**Comment by petarvujovic98** [comment]
@volovyks That is something that we worked on at NF Edu a few months ago, so it could change. But what is the current standard for linting rules?

**Comment by volovyks** [comment]
There is no one standard at the moment. But if I would create one - it should be based on what we have in near-api-js. It is the biggest JS project. Also, with time we are planning to move other JS projects to that repo. The first steps are already made.

**Comment by volovyks** [comment]
I even think that it can be a subproject in near-sdk-js repo.

**Comment by petarvujovic98** [comment]
So what repo is going to be the monorepo? near-sdk-js? near-api-js?

**Comment by volovyks** [comment]
Sory, typo. It's near-api-js.
https://github.com/near/near-api-js

**Comment by ailisp** [comment]
Being addressed in #213
