### ISSUE TITLE
Hide exposed utility functions in collections

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-js#113]
Some utility functions, which should not be exposed publicly, should just be converted into internal functions to avoid confusion and make this change less breaking in the future.

Offending functions: [https://github.com/near/near-sdk-js/blob/37965b8b1f5f467761938229fedf9cd0532cfd24/src/collections/unordered-map.js#L35-L51](https://github.com/near/near-sdk-js/blob/37965b8b1f5f467761938229fedf9cd0532cfd24/src/collections/unordered-map.js#L35-L51)

[https://github.com/near/near-sdk-js/blob/37965b8b1f5f467761938229fedf9cd0532cfd24/src/collections/unordered-set.js#L23-L33](https://github.com/near/near-sdk-js/blob/37965b8b1f5f467761938229fedf9cd0532cfd24/src/collections/unordered-set.js#L23-L33)

[https://github.com/near/near-sdk-js/blob/master/src/collections/vector.js#L23-L28](https://github.com/near/near-sdk-js/blob/master/src/collections/vector.js#L23-L28)

**Comment by ailisp** [comment]
Duplicated with #83

**Comment by austinabell** [comment]
> Duplicated with #83

oops, I really do have a bad memory 😂
