### ISSUE TITLE
Standalone contract function name conflicting issue

### ISSUE THREAD

**Issue by ailisp** [near/near-sdk-js#121]
If user write the contract method name same as one of C function, it would case build or execute fail, depending on which is conflict. Need to figure out a way to address this kind of confliction

**Comment by osalkanovic** [comment]
@ailisp Maybe one of solutions can be to write script to load raw` builder.c ` and to match functions with regex, after that to check before build does any method from contract include matched functions from builder

**Comment by ailisp** [comment]
Good idea!

**Comment by ailisp** [comment]
Fixed in #346
