### ISSUE TITLE
yarn install in `tests/` or `example/` circularly include near-sdk-js/tests and examples

### ISSUE THREAD

**Issue by ailisp** [near/near-sdk-js#146]
Every time I change something in SDK and rebuild examples, I `yarn build` in root directory and remove the near-sdk-js dependency from `tests/` or `examples/`, then re-add near-sdk-js to package.json and redo yarn to make near-sdk-js update. (If just run `yarn` in `tests/` or `examples/` doesn't take the changes). However, yarn install in `tests/` or `example/` appears to circularly include near-sdk-js/tests and examples and result in 500K+ dependencies in yarn link dependency step, very slow, and after a few times, `~/.cache/yarn` increase to more than 200 GB

I also tried yarn link near-sdk-js, but near-sdk-js cli seems not working with this symlinked path. 

@volovyk-s What is your workflow if you update something on sdk-js ts files and use the change in examples? Is it better?

**Comment by volovyk-s** [comment]
@ailisp my workflow is to delete `examples/node_modules` and run yarn. That is why we have `rebuild` command.
But the situation with circular deps is not ok, we need to fix it.

**Comment by ailisp** [comment]
@volovyk-s your workflow seems same to me. Is there a way to avoid `yarn` install `examples/` and `tests/`? That two caused circular dependency. A way may solve this problem: have root `yarn build` build into a tar that has same content as a published npm package, no examples or tests. Then in `examples/` depends on that tar. This may also avoid delete `example/node_modules` to update dependency :thinking:

**Comment by volovyk-s** [comment]
Looks like we need to `npm link` dependencies to avoid `rebuilding`. I need to test if it will help with circular dependencies.

**Comment by ailisp** [comment]
I think it will help with circular dependencies. Last time I tried `yarn link` the sdk-js cli has some path issue (possibly due to the node_modules' structure changed in the link case. It isn't a bug since installed sdk-js work well, but need to special handle to support both installed and linked
