### ISSUE TITLE
Rollup fails witn Node v16.6.0

### ISSUE THREAD

**Issue by volovyks** [near/near-sdk-js#15]
We should understand why this is happening and fix the bug or set supported versions of Node. Works fine with Node v16.14.2

**Comment by ailisp** [comment]
set supported versions of Node sounds good for now

**Comment by Olyno** [comment]
Hi 👋🏻 Do you have more details about this problem? Such as logs, or error messages?

**Comment by Olyno** [comment]
I created a PR to specify the compatible Node versions as suggested. I got details about the Node 16.6.0 problem, available here: https://github.com/babel/babel/discussions/15015#discussioncomment-3801654
