### ISSUE TITLE
post-install script breaks on `aarch64` platform

### ISSUE THREAD

**Issue by maxhr** [near/near-sdk-js#159]
From my (limited) understanding or archs, `aarch64` and `arm64` are the same.

This checks doesn't allow installation to pass on aarch64:
https://github.com/near/near-sdk-js/blob/develop/cli/post-install.js#L11

For me it breaks inside a **Docker container** on my mac, and it doesn't break outside the container.

**Comment by volovyk-s** [comment]
@maxhr please, check if it works if you use code from the [attached PR](https://github.com/near/near-sdk-js/pull/163).

**Comment by maxhr** [comment]
@volovyk-s it fails on:
`wget https://github.com/near/binaryen/releases/download/v0.1.10/binaryen-Linux-arm64.tar.gz`
says `HTTP 404`

Inside a Docker container from `node:alpine` image i have:
```
uname -s -> Linux
uname -m -> aarch64
uname -a -> Linux ed3742d9a6a2 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64 Linux

**Comment by volovyk-s** [comment]
We do not have a build for ARM Linux, what machine are you using?
I do not have such hardware, we need to add one more release here: https://github.com/near/binaryen/releases/tag/v0.1.10

**Comment by volovyk-s** [comment]
Ideally, it should be one more job here: https://github.com/near/binaryen/blob/main/.github/workflows/release-artifacts.yml

**Comment by ailisp** [comment]
done in #393
