### ISSUE TITLE
post-install: consider alternative to `wget`

### ISSUE THREAD

**Issue by maxhr** [near/near-sdk-js#160]
One of our users didn't have `wget` on his platform (mac) and post-install broke for him:
https://github.com/near/near-sdk-js/blob/develop/cli/post-install.js#L23

Please consider a more robust way to download deps.

**Comment by volovyk-s** [comment]
Not sure if there is a way to download something from the web with the tool that is preinstalled on all platforms. But I agree, we need to check if it is available and throw a nice error or propose to install it.

**Comment by thisisjoshford** [comment]
I think [curl ](https://curl.se/) would be a better alternative to wget as comes with most Linux distros, ships with macOS, as well as Windows 10.
