### ISSUE TITLE
Add Key With Full Access Raises Error

### ISSUE THREAD

**Issue by gagdiez** [near/near-sdk-js#164]
I am implementing the documentation on Actions for js. While making the docs for adding a full access key I kept bumping into the `VM Logic provided an invalid public key` error.

The interesting thing is that I used the same key in other examples and it worked.

The example I am making is here: https://near-docs-pr-1119.onrender.com/develop/contracts/actions#add-keys

**Comment by ailisp** [comment]
I think you did not give the key in acceptable format. This test works:
```
export function test_promise_add_full_access_key() {
    let promiseId = near.promiseBatchCreate('c.caller2.test.near')
    near.promiseBatchActionCreateAccount(promiseId)
    near.promiseBatchActionTransfer(promiseId, 10000000000000000000000000n)
    near.promiseBatchActionAddKeyWithFullAccess(promiseId, near.signerAccountPk(), 1n)
    near.promiseReturn(promiseId)
}
```
So I look at `near.signerAccountPk()`, it calls nearcore's signer_account_pk() in logic.rs, which returns this PublicKey in bytes:
```
pub enum PublicKey {
    /// 256 bit elliptic curve based public-key.
    ED25519(ED25519PublicKey),
    /// 512 bit elliptic curve based public-key used in Bitcoin's public-key cryptography.
    SECP256K1(Secp256K1PublicKey),
}
```
The bytes is borsh serialized. For the typical ED25519 key, the encoding is a byte 0, following 32 byte ed25519 public key in binary (You can get it by loading the key with near-api-js and log). I confirm `near.signerAccountPk()` is in this format.

**Comment by ailisp** [comment]
@gagdiez does above format work for you?

**Comment by ailisp** [comment]
I believe above test proves it is working with binary format public key. We also have a more friendly API, takes `ed25519:...` format key: `PublicKey.fromString`, introduced in #181, which is probably you want to use.
