### ISSUE TITLE
BigInt serialization support

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-js#172]
The `BigInt` type used throughout the library errors on `JSON.serialize` ([by design](https://github.com/GoogleChromeLabs/jsbi/issues/30)) but is a footgun for developers.

My intuition is that something like [the suggestion on the linked issue](https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-521449285), except just including the receiver function to the JSON.stringify, might be sufficient for our internal JSON serializing of state.

The issue is that deserializing might not be so straightforward since, from a string we may not be able to infer the return type based on the `JSON.parse` function signature.

JS is so wonderful. Maybe if there is a way at the SDK level to override the stringify and parse methods of BigInt, similar to what [this comment](https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-1006088574) suggests, might be the cleanest?

**Comment by ailisp** [comment]
I was just about to create the same issue. Thanks!

> JS is so wonderful. Maybe if there is a way at the SDK level to override the stringify and parse methods of BigInt, similar to what https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-1006088574 suggests, might be the cleanest?

Good idea!
