### ISSUE TITLE
Unnecessary `default` function semantics with SDK

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-js#173]
Issue opened more as discussion, but the `default` function feels redundant that should just be handled by the constructor.

for example, the status message contract:
```ts
@NearBindgen
class Counter extends NearContract {
    constructor({ initial = 0 }) {
        super()
        this.count = initial
    }
    // ...
    default() {
        return new Counter({ initial: 0 })
    }
}
```

it doesn't make sense why this could not be:
```ts
@NearBindgen
class Counter extends NearContract {
    constructor() {
        super()
        this.count = 0
    }
    // ...
}
```

Or even allow specifying named parameters with the defaults in the constructor. The code duplication and unnecessary boilerplate (including `default() {return new <Class Name>()}`) feels unnecessary. Having specific requirements around a `default` function won't be clear to developers without documentation and acts like an eDSL.

**Comment by gagdiez** [comment]
@austinabell there is an ongoing discussion on how to improve this in https://github.com/near/near-sdk-js/pull/169.
