### ISSUE TITLE
Support for `promise_batch_action_function_call_weight`

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-js#175]
Assumed this would be used by the SDK, but this simplifies the devX a lot because it doesn't require someone to specify gas explicitly. I have noticed developers having issues with this getting started.

There isn't really a clear path to migrate the APIs without being breaking. Basically what needs to happen is `gas` being made optional and also including the optional parameter of `gasWeight`. Possibly a non-breaking change would be to make `gas` optional and just add `gasWeight` as the next positional argument, which is not ideal because it requires specifying a gas value if you only want to modify the weight, and these can be confused.

The builder would have to be modified to include (or change) the existing `near_promise_batch_action_function_call` to call the updated runtime host function.

**Comment by ailisp** [comment]
Great demostration on `promise_batch_action_function_call_weight`. We also need to figure out integration of protocol version in build cli, to include recent and future APIs.
