### ISSUE TITLE
Error Message Request: Existing info in LookupMap

### ISSUE THREAD

**Issue by doriancrutcher** [near/near-sdk-js#191]
Let's say you have a lookup map in your smart contract and you set the key as `name` and the value as `Dorian` 

Then you run the method again placing the same value `Dorian` under the key `name` 

the current error message received is 

```
"Smart contract panicked: unexpected token: 'undefined'\n"
```

Which is a bit misleading to what's actually going on. 

Could the message be something like `value already exists`?

**Comment by ailisp** [comment]
This looks like a bug, we're expecting `set` to work when value already exists
