### ISSUE TITLE
Feature Request: Vector "Includes" 

### ISSUE THREAD

**Issue by doriancrutcher** [near/near-sdk-js#193]
In javascript you can run this method called "includes" to check for the existence of a value within an array, it would be really useful if the `vector collection` inside of the near-sdk-js can do the same thing.

**Comment by ailisp** [comment]
The vector collection is designed for very large arrays. It place each value in a different key in trie, so naturally this design is fast to get/append (don't need to reserailize the whole array), but impractically expensive to iterate. `includes` API would need to iterate all values of the vector, and would exceed the gas limit for a large vector. If you're sure the vector won't grow big (e.g. one element per user), you can store a JS array directly in contract, or use `Vector.toArray` to turn Vector into a JavaScript array and call JS's `includes` on that!
