### ISSUE TITLE
Adding instance type for vector, maps and sets

### ISSUE THREAD

**Issue by osalkanovic** [near/near-sdk-js#199]
It would be beneficial to include instance type in vector, maps and sets. Something as `users = new Vector<User>().` Because overriding an instance with a type assertion ('as') is occasionally very painful

If you'd like, I can push a solution because I have a working example. 😄

**Comment by volovyks** [comment]
Hey @osalkanovic ! We have made experiments in this direction, but serialization/deserialization appeared to be problematic. I would love to see your solution!

**Comment by ailisp** [comment]
Implemented by @osalkanovic :tada: !
