### ISSUE TITLE
Collection nesting

### ISSUE THREAD

**Issue by petarvujovic98** [near/near-sdk-js#202]
I am having some issues storing an UnorderedMap inside an object inside an UnorderedMap.

What I am trying to do is something like this:
```typescript
class Inner {
  public innerMap: UnorderedMap = new UnorderedMap("v");
}

@NearBindgen
class Contract extends NearContract {
  outerMap: UnorderedMap;
  
  constructor() {
    this.outerMap = new UnorderedMap("o");
  }

  default() {
    return new Contract();
  }

  @call
  add({ id, text }) {
    const inner = this.outerMap.get(id);
    inner.innerMap.set(near.signerAccountId(), text);
  }
}
```

The problem is that the `innerMap` doesn't get deserialized into an `UnorderedMap` object, and there is no API to construct it manually (like say a `from` function).

Any advice on how to accomplish this or implement the deserialization automatically?
I'd be happy to work on a PR for it

**Comment by ailisp** [comment]
Unfortunalely we don't have a way to deserialize and restore the type automatically. A manually example can be seen here: https://github.com/near-examples/nft-tutorial-js/blob/7695f16e3bc0baae78742a82e0059f0a64794518/src/nft-contract/internal.ts#L6. For any usage on your `innerMap`, use this restore function on the innerMap before call method on it: https://github.com/near-examples/nft-tutorial-js/blob/7695f16e3bc0baae78742a82e0059f0a64794518/src/nft-contract/internal.ts#L79 (The example is a innerSet, but it's the same for a innerMap)

**Comment by volovyks** [comment]
@ailisp since both these types have a `deserialize()` function, theoretically, it is possible to deserialize the whole object recursively. What do you think?

**Comment by petarvujovic98** [comment]
@volovyks I think it is quite difficult to make this automatic as it requires embedding type information into the serialized object and based on that performing the appropriate `deserialize()` call on deserialization. Just having the deserialize function for each collection more visible and documented would be great.

P.S. This discussion [here](https://github.com/near/near-sdk-js/pull/203#discussion_r964322491) is related to this issue.

**Comment by petarvujovic98** [comment]
@volovyks Yeah, it would need some recursion to allow for nested collections. [This](https://github.com/near/near-sdk-js/blob/develop/src/near-bindgen.ts#L56) would only go 1 level deep.

**Comment by ailisp** [comment]
Agree with the points above. 

> not sure how it will work with nested collections.

Seems challenging. Take this as example, the most straightforward nested collection: `LookupMap<String, LookupSet<String>>`. Current `LookupMap.get`:
```
    get(key: Bytes): unknown | null {
        let storageKey = this.keyPrefix + JSON.stringify(key)
        let raw = near.storageRead(storageKey)
        if (raw !== null) {
            return JSON.parse(raw)
        }
        return null
    }
```

if we could do  `_reconstruct(LookupSet, JSON.parse(raw)) `, we would solve this problem, but `LookupMap` doesn't know its value is `LookupSet`. In this case we might store a `LookupSet` instance as LookupMap's "valueType" property.
If it was one level more: `outerMap: LookupMap<String, LookupSet<UnorderedMap<String, Y>>>`, we can set `outerMap.valueType = new LookupSet({valueType: new UnorderedMap({valueType: Y})) `, this seems not quite automatic, a lot of runtime type anotation.

**Comment by ailisp** [comment]
We now have necessary generic collections, reconstruct mechanism in #203 and customized serializer/deserializer option in #213. I think a good example will show how collection nesting will work now, which is in #231

**Comment by ailisp** [comment]
collection example is done, so this issue is done too as described above.
