### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by petarvujovic98** [near/near-sdk-js#205]
Right now there are no JSDoc comments in the exposed API. This, along with better TypeScript type definitions, is key for DX as it speeds up workflows by making it so that developers don't have to go to the browser to have explanations about the functions and parameters they want to use/pass to those functions. IDEs are just going to show you the documentation on hover.

Also having more descriptive names for functions, parameters and generic parameters/types is a self documenting way of helping the developers have a lesser overhead when developing

**Comment by ailisp** [comment]
Majority is addressed in #252, now only a few host functions (hashing, crypto primitives, etc.) are missing and JSDoc site generation
