### ISSUE TITLE
Contract fields not serialized

### ISSUE THREAD

**Issue by petarvujovic98** [near/near-sdk-js#210]
If there is a field in the contract which does not have a default value or is not assigned a default value in the constructor it will not be able to be initialized or saved later. 
Here is a minimal snippet for which a test checking presence of the variable after writing fails:
`contract.ts`
```typescript
import { NearBindgen, near, call, view } from "near-sdk-js";

@NearBindgen({})
export class HelloNear {
  private owner: string;

  @call({})
  set_owner({ owner }): void {
    this.owner = owner;
    near.log(`Set owner to ${this.owner}`);
  }

  @view({})
  get_owner(): string {
    return this.owner;
  }
}
```
`main.ava.ts`
```typescript
import { Worker, NearAccount } from "near-workspaces";
import anyTest, { TestFn } from "ava";

const test = anyTest as TestFn<{
  worker: Worker;
  accounts: Record<string, NearAccount>;
}>;

test.beforeEach(async (t) => {
  // Init the worker and start a Sandbox server
  const worker = await Worker.init();

  // Deploy contract
  const root = worker.rootAccount;
  const contract = await root.createSubAccount("test-account");
  // Get wasm file path from package.json test script in folder above
  await contract.deploy(process.argv[2]);
  // await contract.call(contract, "init", { owner: contract.accountId });

  // Save state for test runs, it is unique for each test
  t.context.worker = worker;
  t.context.accounts = { root, contract };
});

test.afterEach(async (t) => {
  // Stop Sandbox server
  await t.context.worker.tearDown().catch((error) => {
    console.log("Failed to stop the Sandbox:", error);
  });
});

test.only("test", async (t) => {
  const { contract } = t.context.accounts;
  const owner = "123";

  await contract.call(contract, "set_owner", { owner });
  const savedOwner = await contract.view("get_owner");

  t.is(savedOwner, owner);
});
```

This applies to contracts which require initialization also:
`contract.ts`
```typescript
import { NearBindgen, near, call, view, initialize } from "near-sdk-js";

@NearBindgen({ requireInit: true })
export class HelloNear {
  private owner: string;

  @initialize({})
  init({ owner }): void {
    this.owner = owner;
  }

  @call({})
  set_owner({ owner }): void {
    this.owner = owner;
    near.log(`Set owner to ${this.owner}`);
  }

  @view({})
  get_owner(): string {
    return this.owner;
  }
}
```
`main.ava.ts`
```typescript
import { Worker, NearAccount } from "near-workspaces";
import anyTest, { TestFn } from "ava";

const test = anyTest as TestFn<{
  worker: Worker;
  accounts: Record<string, NearAccount>;
}>;

test.beforeEach(async (t) => {
  // Init the worker and start a Sandbox server
  const worker = await Worker.init();

  // Deploy contract
  const root = worker.rootAccount;
  const contract = await root.createSubAccount("test-account");
  // Get wasm file path from package.json test script in folder above
  await contract.deploy(process.argv[2]);
  await contract.call(contract, "init", { owner: contract.accountId });

  // Save state for test runs, it is unique for each test
  t.context.worker = worker;
  t.context.accounts = { root, contract };
});

test.afterEach(async (t) => {
  // Stop Sandbox server
  await t.context.worker.tearDown().catch((error) => {
    console.log("Failed to stop the Sandbox:", error);
  });
});

test.only("test", async (t) => {
  const { contract } = t.context.accounts;
  const owner = "123";

  await contract.call(contract, "set_owner", { owner });
  const savedOwner = await contract.view("get_owner");

  t.is(savedOwner, owner);
});
```

**Comment by petarvujovic98** [comment]
@volovyks I would be against the **@persist** decorator, by default we would want everything persisted. There might be a case for a **@ignore** decorator to _not_ persist something, but IMO even this is questionable as you could just construct the value inside the function body. 

I'll have to look into the `near-bindgen` logic more to make a better guess on design.

**Comment by volovyks** [comment]
I like the @ignore idea.

**Comment by gagdiez** [comment]
Sadly that is the nature of non-typed languages, de-serializing without knowing what is serialized is simply not possible.

For now, I think needing to have everything initialized with a default value is a good enough trade-off.

I think that, with the inclusion of "requireInit" and "private" this will be less of a problem, since there are two possible cases:

1) you want a default state, for which the "declaration" values will be used, therefore they need to be defined
2) you want to have a forced init, in which case "requireInit" and "private" will be used, for which the "declaration" values will only be used to deserialize once, therefore not affecting the contract.

**Comment by petarvujovic98** [comment]
@gagdiez I agree. We need to make this clear in docs and tutorials. I think adding comments to the `create-near-app` template contract about this is also important.

**Comment by volovyks** [comment]
I have added info here: https://github.com/near/near-sdk-js/pull/211#pullrequestreview-1100521753
Yes, It would be great to have it in docs and create-near-app as well. Closing this issue for now. Feel free to reopen it if you have design ideas.
