### ISSUE TITLE
View Methods Still Require Deserialization After 0.5.0

### ISSUE THREAD

**Issue by idea404** [near/near-sdk-js#214]
Using smart contract in https://github.com/near-examples/coingecko-oracle, view method would break tests unless the contract state was extracted into a JS object before returning as follows: 

```js
  @view({})
  getPrices({}) {
    const prices = { ...this.near_prices };
    return prices;
  }
```

Is this correct? Why can't the contract just have `return this.near_prices;`?

**Comment by volovyks** [comment]
@idea404 I have updated SDK, Workspaces, and changed the code to
```JS
@view({})
getPrices() {
    return this.near_prices;
}
```
works just fine.
https://github.com/near-examples/coingecko-oracle/pull/4

P.S. Have not tried to fix server tests.
