### ISSUE TITLE
[Question] - Any Roadmap/plan?

### ISSUE THREAD

**Issue by Olyno** [near/near-sdk-js#216]
Hi 👋🏻 
I wish I could contribute to the JS/TS part of Near in many ways, but can't find a roadmap. 

So my question is: how does the organization work for the JS/TS part (near-sdk-js and create-near-app)? How are the pull requests merge? Are there any tasks where we could help?

**Comment by ailisp** [comment]
Hi @Olyno I noticed you're helping near-sdk-js in high enthusiastic! We're very appreciate on your contribution! Previously we're mostly catching up near-sdk-rs's progress, from 2.0 to currently somewhere between 3.0 and 4.0. Recently, we have increasing contributions from highly capable open source community, like you. And we'll be more ambitious and also make it clear on what and how you can help in the most comfortable way.

**Therefore, we'll have a meeting later this week to figure out your questions.** Will keep you updated!

**Comment by Olyno** [comment]
Hi @ailisp Awesome! Can't wait to work on the project with you guys!

**Comment by ailisp** [comment]
Hi @Olyno, thanks for your patience! After a few meeting and discussions, we finalize a roadmap! Please check github issue labels, `v0.6`, `v0.7`, `v1.0` and `v1.0+` indicates the timeline they are expected to addressed or implemented. If you are interested to contribute, it would be great to start from a `v0.6` issue that doesn't link with a pull request
