### ISSUE TITLE
Unusable nested collections

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-js#217]
Currently the storage collections are only setup to work when part of the root state. The issue is that since the storage get has an `unknown` return type, you can't have it typed as a collection type:

```ts
// This doesn't work
const map: UnorderedMap = this.records.get("test");
```

Which is very unergonomic because the [deserialize function requires that as the type](https://github.com/near/near-sdk-js/blob/91dec294f559dc924c0f8854d908824d2155e63b/src/collections/unordered-map.ts#L109).

This takes us to the next point, that deserialize is required when loading the value. This might be necessary with JS, but at least the nested collections pattern should be documented, but also have this deserialize function type be improved so you don't need to cast as `any`.

The code for a nested example is as follows:

```ts
import { NearBindgen, call, view, near, UnorderedMap } from "near-sdk-js";

@NearBindgen({})
class StatusMessage {
  records: UnorderedMap;
  constructor() {
    this.records = new UnorderedMap("a");
  }

  @call({})
  set_status({ message, prefix }: { message: string; prefix: string }) {
    let account_id = near.signerAccountId();

    const inner: any = this.records.get("b" + prefix);
    const inner_map: UnorderedMap = inner
      ? UnorderedMap.deserialize(inner)
      : new UnorderedMap("b" + prefix);

    inner_map.set(account_id, message);

    this.records.set("b" + prefix, inner_map);
  }

  @view({})
  get_status({ account_id, prefix }: { account_id: string; prefix: string }) {
    const inner: any = this.records.get("b" + prefix);
    const inner_map: UnorderedMap = inner
      ? UnorderedMap.deserialize(inner)
      : new UnorderedMap("b" + prefix);
    return inner_map.get(account_id);
  }
}
```

Where it seems to be error-prone for people figuring this out.

**Comment by ailisp** [comment]
We have a few of discussions about this problem. What you suggested seems to be the current working pattern. In @BenKurrek 's NFT example, he wrapped the logic to get inner map to a helper function, but it's essentially same pattern.

@osalkanovic and @petarvujovic98 figured out an elegant approach, that turn UnorderedMap.get take an optional argument to restore the obtained value to its type: https://github.com/near/near-sdk-js/pull/203. We think this approach is a great general solution that will be documented. Let us know your thoughts of #203 !

**Comment by austinabell** [comment]
Oops! Didn't see the other issue related to this :) feel free to close and use other to track, if you think that PR solves both of this issues problems.

**Comment by volovyks** [comment]
I am closing this issue in favor of https://github.com/near/near-sdk-js/issues/202. Let's continue our discussion there.
