### ISSUE TITLE
State issue needs clarification (hackathon feedback)

### ISSUE THREAD

**Issue by bucanero** [near/near-sdk-js#224]
From: @aut-protocol https://github.com/Aut-Protocol/Aut-on-NEAR/blob/main/protocol/pagoda_journey.md

Make it super clear in the docs that the state won't work if it's not initalized when set as a property, even if it does in the initializer. Example:

```js
//prop: string;
prop: string = '';

@initialize({})
init() {
    this.prop = 'initial value'
}
```

**Comment by volovyks** [comment]
It is mentioned in README: https://github.com/near/near-sdk-js#nearbindgen-and-other-decorators
```
Your class must have a constructor(). You will not be able to call it, which is why it should not accept any parameters. You must declare all the parameters that you are planning to use in the constructor and set default values.
```
But yes, let's make it more clear.

**Comment by volovyks** [comment]
I wonder if there is something like 'strict' mode that will require users to do that.

**Comment by osalkanovic** [comment]
@volovyks its possible by adding condition in babel transformer like this
```typescript 
if(child.kind == 'constructor') {
              hasConstructor = true;
}
```

If you want I can create PR :)
