### ISSUE TITLE
No autocomlition in TS contracts

### ISSUE THREAD

**Issue by volovyks** [near/near-sdk-js#246]
The contract can be built, but import shows an error in VSCode.
![image](https://user-images.githubusercontent.com/4030422/192253479-a3a92d98-ae78-4173-b456-00a79d449382.png)
The issue is present in 0.5 but 0.4 works fine.

**Comment by petarvujovic98** [comment]
There is a fix for this in the #228 PR

**Comment by volovyks** [comment]
Great, thanks @petarvujovic98 !
