### ISSUE TITLE
Middlewares

### ISSUE THREAD

**Issue by osalkanovic** [near/near-sdk-js#256]
It would be good to have `@middleware` decorator

Example: 
```typescript
import {middleware, Middleware, near} from "near-sdk-js"

class OwnerValidator implements Middleware {
   
   call(data, next) {
     if(near.predecessorAccountId() != "test.near.org") //throw error
     next()
   }
}

....

@middleware(OwnerValidator)
@call()
create_user(){}

```

It has many advantages such as data validation, deposit validation, etc
I don't think it will be a big challenge to implement this.  If you guys agree, I'd love to implement this

@ailisp @volovyks

**Comment by ailisp** [comment]
Looks like a nice addition to SDK! @volovyks what do you think?

**Comment by volovyks** [comment]
Hm... I like the idea to automate common actions. But maybe some of them (like the one above), can be a parameter in @call decorator.
@osalkanovic do you have a link with the implementation? Can it live outside of the repo? (we can use it in our examples).

**Comment by gagdiez** [comment]
@osalkanovic  is there something similar in the rust sdk?

**Comment by osalkanovic** [comment]
> Hm... I like the idea to automate common actions. But maybe some of them (like the one above), can be a parameter in @call decorator. @osalkanovic do you have a link with the implementation? Can it live outside of the repo? (we can use it in our examples).

I dont have example, I just recommend as idea

**Comment by osalkanovic** [comment]
> @osalkanovic is there something similar in the rust sdk?

I think no :D

**Comment by petarvujovic98** [comment]
I think #263 closes this.

**Comment by volovyks** [comment]
Yes, thank you @petarvujovic98
And thank you for the idea @osalkanovic
