### ISSUE TITLE
Collections inside Classes don't work

### ISSUE THREAD

**Issue by therealharpaljadeja** [near/near-sdk-js#264]
```ts
export class Event {
    title: string;
    active: boolean;
    timestamp: number;
    amountCollected: number;
    host: Host;
    tickets: UnorderedSet;

    constructor({
        title,
        active,
        timestamp,
        amountCollected,
        hostName,
        hostAccountId,
    }) {
        this.title = title;
        this.active = active;
        this.timestamp = timestamp;
        this.host = new Host({ name: hostName, accountId: hostAccountId });
        this.amountCollected = amountCollected;
        this.tickets = new UnorderedSet(title);
    }
}
```

```ts
event.tickets.set(something)
```

throws not a function!

**Comment by volovyks** [comment]
@therealharpaljadeja can you please share a simplistic contract that can actually be compiled?

**Comment by therealharpaljadeja** [comment]
@volovyks please the contract and a test file at this URL 

https://gist.github.com/therealharpaljadeja/8d42a6ed01968f8c55ae552ccd3792ef

If there is no solution please suggest a workaround, I am participating in the hackathon and need to complete this, thanks!

**Comment by volovyks** [comment]
@therealharpaljadeja you must have a constructor in your contract class where you initialize all the properties.

**Comment by therealharpaljadeja** [comment]
In `Events`, the only property is already initialized; the error isn't even coming from there. The error is in `buyTicket` function 

```ts
event.tickets.set(ticket)
```

**Comment by ailisp** [comment]
As Serhii said, you have to have a constructor in `Events` to initialize fields instead of initialize them outside the constructor. like this:
```
@NearBindgen({})
export class Events {
    createdEvents: UnorderedMap<Event>;

    constructor() {
        this.createdEvents = new UnorderedMap("events");
    }
```

This is not a constraint from TypeScript, but from our SDK, to get the generated contract works properly. Sorry about that!

**Comment by volovyks** [comment]
@therealharpaljadeja I think the last SDK version should prevent that by throwing an error during the build process. @therealharpaljadeja please upgrade.

**Comment by ailisp** [comment]
Closed as it's enforced to write in ^ above way and if so it works, otherwise latest near-sdk-js cli will throw error.
