### ISSUE TITLE
JS SDK `v0.6.0` adds `ts-morph` devDependency

### ISSUE THREAD

**Issue by idea404** [near/near-sdk-js#284]
Upgrading repo from v0.5 to v0.6 threw the following error: 

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/10233439/199951573-60eb4260-ff20-4bab-a0c8-9ced5b4a3cdd.png">

This was addressed by adding `ts-morph` to the project devDependencies. Is this intended behavior? Is it not a little forced to require developers to add another dependency they do not expect when using this library?

**Comment by ailisp** [comment]
Good finding! I think ts-morph should be a dependency of near-sdk-js instead of a dev dependency of near-sdk-js. Let's fix it!

**Comment by volovyks** [comment]
@idea404 since you already fixed it, can you please crate the PR?
