### ISSUE TITLE
UnorderedMap And Unordered Set Should Have a Way to Return Keys

### ISSUE THREAD

**Issue by doriancrutcher** [near/near-sdk-js#302]
I was writing an example and realized that an UnorderedMap and an Lookup Map should have a way to return all the keys within the collection. 

In my example I had to store the keys separately in an UnorderedSet to be able to. accomplish this which seems like a redundant use of storage.

**Comment by ailisp** [comment]
Currently, you can use this way to retrieve all keys of your UnorderedMap:
```js
    for (let i = 0; i < m.length; i++) {
      const k = m.keys.get(i);
// k is the key.
    }
```

**Comment by volovyks** [comment]
@doriancrutcher do you think this solution is good enough? Or do you want to have a separate function for that? And is there any diff compared to the Rust version?

**Comment by ailisp** [comment]
Suggested API is added in #337
