### ISSUE TITLE
The `initalization` decorator doesn't accept `privateFunction` argument

### ISSUE THREAD

**Issue by wzard** [near/near-sdk-js#326]
Unlike the `call` decorator which accepts `privateFunction` argument to make the method `private`, the `initialization` decorator doesn't seem to accept the `privateFunction` argument. 

I believe this has been wrongly used in the [example-donation-contract.ts](https://github.com/near-examples/donation-js/blob/47b38b10bcbe10392816adef20e8c0cb02a86996/contract/src/contract.ts#L11).

This makes the task of making the `init` function `private` by using the following way:

```js
  @initialize({ })
  @call({ privateFunction: true})
  init({ count }: { count: string }) {
     // Function body
  }
``` 

This seems less than ideal. I believe making the `initialization` decorator accept `privateFunction` argument will be a better way of making `init` methods private. Thoughts?

**Comment by volovyks** [comment]
It's not there because it is expected that you will initialize the contract during deployment. But I already saw this complaint and maybe we should add it for consistency reasons.

**Comment by wzard** [comment]
Makes sense. Closing the issue as this is a non-issue.
