### ISSUE TITLE
Add contribution guideline

### ISSUE THREAD

**Issue by ailisp** [near/near-sdk-js#327]

**Comment by thisisjoshford** [comment]
@maxhr just shipped contribution guidelines to NAJ
https://github.com/near/near-api-js/pull/1037

Does this format work for you @ailisp ?

**Comment by ailisp** [comment]
Yeah, it is great. Thank you so much! Max's format and excellent writing will save us a huge effort. I think we're good to start from there, make some sdk specific changes and asking DevRel for review.

**Comment by thisisjoshford** [comment]
Awesome, @maxhr can you modify the contribution guidelines you created in NAJ and open a PR in this repo?
