### ISSUE TITLE
Generate JS Doc site and host it

### ISSUE THREAD

**Issue by ailisp** [near/near-sdk-js#333]

**Comment by thisisjoshford** [comment]
@idea404 just shipped these reference docs for JS SDK
https://docs.near.org/sdk/js/introduction

Does this suffice or are you looking to create a standalone 
typedocs site?

**Comment by ailisp** [comment]
Wow this is a great work! I think what Dennis created will cover 90%+ cases, and we still want a typedocs as a supplementary. All doc strings are already there, thanks to @petarvujovic98 , what missing is generating, theme and host under near docs.

**Comment by thisisjoshford** [comment]
Ok sounds good! I'll create a ticket for it with my team @ailisp.
cc @maxhr @idea404 @gagdiez

**Comment by ailisp** [comment]
Accomplished by @doriancrutcher ! https://docs.near.org/sdk/near-sdk-js/reference
