### ISSUE TITLE
Can't return Object from function

### ISSUE THREAD

**Issue by BenKurrek** [near/near-sdk-js#34]
I can't seem to return an object from my function. This is the code I have right now where `boardState` is: 
```js
this.boardState = {
    "row1": 1,
    "row2": 2,
    "row3": 3,
    "row4": 4,
    "row5": 5
}
```
```js
/*
        get the current state of the smart contract. This includes:
        full board state, player 1, 2, current turn, whether the game is active or not.
    */
    @view
    getState() {
        env.log("Get state called!")
        for (const row in this.boardState) {
            env.log(`${row}: ${this.boardState[row]}`);
        }
        env.log(`player one: ${this.playerOne}`);
        env.log(`player two: ${this.playerTwo}`);
        env.log(`current turn: ${this.currentTurn}`);
        env.log(`game active: ${this.isGameActive}`);

        return this.boardState;
    }
```

Here is an example transaction: https://explorer.testnet.near.org/transactions/F4j71D9f5G6yvHRgvAyLzd5TsLzRpUYyQvZQDM3tMLjp

The object isn't being returned for some reason. A link to my repo can be found [here](https://github.com/BenKurrek/near-sdk-js-game/blob/main/readme.md)

**Comment by ailisp** [comment]
If you do not attach deposit it should work, or call it with `view_js_contract`. The problem is described in #3. In short, NEAR cannot return both value (your returned project) and promise (refund your deposit).

**Comment by BenKurrek** [comment]
Ah ok - is this in the pipeline to be fixed before the release of the SDK?
