### ISSUE TITLE
Remove warning relevant for v 0.7 but is now fixed

### ISSUE THREAD

**Issue by vikpande** [near/near-sdk-js#354]
### Prerequisites

- [X] I'm using the latest version of `near-sdk-js`.
- [ ] I have tried to start with a fresh project and reproduce the defect with minimal code changes.
- [ ] I have read the console error messages carefully (if applicable).

### Description

Remove warning from js-sdk from the documentation thats now updated with the release of v 1.0+.

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/15668152/232401351-f7a924ed-bc60-4c27-8aaa-00fb5f74b544.png">
 

### Steps to reproduce

1. warning can be seeing when one tries to run sdk js library to build a contract on mainnet

### Expected behavior

No warning shown in the app, hence this should be removed from the documentation as well

### Actual behavior

Remove warning from the documentation

### Your environment

- NEAR JavaScript SDK version used - v.1.0.0

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by ailisp** [comment]
Fixed
