### ISSUE TITLE
Accessing newly created data structures after redeploying the smart-contract doesn't work.

### ISSUE THREAD

**Issue by johnedvard** [near/near-sdk-js#358]
### Prerequisites

- [X] I'm using the latest version of `near-sdk-js`.
- [X] I have tried to start with a fresh project and reproduce the defect with minimal code changes.
- [X] I have read the console error messages carefully (if applicable).

### Description

I encountered a question on SO, https://stackoverflow.com/q/76565036/1471485, and tried to answer it myself.

After debugging the issue, I was able to reproduce the same kind of error:
```
 ExecutionError: "Smart contract panicked: cannot read property 'prefix' of undefined\n" +
      '    at reconstruct (build/hello_near.js:994)\n' +
      '    at _reconstruct (build/hello_near.js:1086)\n' +
      '    at buy (build/hello_near.js:1122)\n'
```

If we look at the built code in `build/hello_near.js:994`, we see the following
```js
static reconstruct(data) {
    const map = new UnorderedMap(data.prefix); // Here, we try to access `prefix` of data that doesn't exists. 
    // reconstruct keys Vector
    map.keys = new Vector(`${data.prefix}u`);
    map.keys.length = data.keys.length;
    // reconstruct values LookupMap
    map.values = new LookupMap(`${data.prefix}m`);
    return map;
  }
```

This makes me believe that the `_reconstruct` function in [near-bingden.ts](https://github.com/near/near-sdk-js/blob/01cab6def3c6a9d55c85d402836df03bf0e32fca/packages/near-sdk-js/src/near-bindgen.ts#L212C23-L212C23) needs some adjustments, though I'm not entirely sure if this is the root cause

## Step 1
1. write contract code:
```js
import { NearBindgen, call, UnorderedMap } from 'near-sdk-js';

@NearBindgen({})
class HelloNear {
  private stocks: UnorderedMap<number> = new UnorderedMap<number>('myPrefix');

  constructor() {
    this.stocks.set('msft', 10);
  }

  @call({})
  getStockPrice(): number {
    return this.stocks.get('msft'); 
  }
}
```

2. Build and deploy.
3. call the function `getStockPrice` -> returns 10. So far so good.

## Step 2
1. Add a new data structure to the existing contract code
```js
@NearBindgen({})
class HelloNear {
  private stocks: UnorderedMap<number> = new UnorderedMap<number>('myPrefix');
  private superStocks: UnorderedMap<number> = new UnorderedMap<number>('mySecondPrefix'); // added this

  constructor() {
    this.stocks.set('msft', 10);
  }

  @call({})
  getStockPrice(): number { // modify this function to read the new data structure 
    if(!this.superStocks.get('msft')) { // contract will panic here.  Cannot read property 'prefix' of undefined\n
      this.superStocks.set('msft', 30);
    }
    return this.superStocks.get('msft'); 
  }
}
```
2. build and re-deploy
3. call the function `getStockPrice` -> Smart contract panics. Cannot read property 'prefix' of undefined\n

### Expected behavior

I expect that we should be able to access the new data structure, `superStocks`, after we redeploy the smart-contract (to the same address.) 

### Actual behavior

Smart contract panics when we try to access the new data structure, `superStocks`: Cannot read property 'prefix' of undefined\n

### Your environment

- NEAR JavaScript SDK version used: 1.0.0
- Relevant dependencies (if applicable): none

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by ailisp** [comment]
@johnedvard Adding a new field to the existing contract require a migration, you can check this example: https://github.com/near/near-sdk-js/pull/363/files#diff-c391d87a2f928a12b5721ad0b5b33df814963f245166d18db035a1c8db1e578fR43

**Comment by ailisp** [comment]
Close as not a bug. If you have question on writing migrations, let us know!
