### ISSUE TITLE
Add/Improve error handling

### ISSUE THREAD

**Issue by ChaoticTempest** [near/near-sdk-js#37]
Currently, a lot of errors or safety checks aren't being handled properly. This issue documents a few of them so we can track progress. This is not exhaustively all of them, so add more as they come in:

*   [ ] deploy: if fed incorrect bytes will do nothing, and later when calling into the contract will get opcode error such as this issue: [https://github.com/near/near-sdk-js/issues/22](https://github.com/near/near-sdk-js/issues/22)

**Comment by ailisp** [comment]
> if fed incorrect bytes will do nothing

This particular one is challenging, as most of the js module quite lazily load so not able to detect many errors until call it. We can do some basic checks.

**Comment by ChaoticTempest** [comment]
hmm, I wonder how expensive it would be to package the JSVM with a basic javascript linter. That way we can decode and check against the bytes for some confidence that it is valid javascript against a threshold

**Comment by ailisp** [comment]
@ChaoticTempest The SDK has been upgraded to write in TS, error checks and safety checks should be better, particularly those compile-time checks. This specific one is related to enclave (jsvm), and isn't relevant for standalone. I'll mark this with `jsvm` label and deprioritize it. If you find other problems in error handling, feel free to create another issue!
