### ISSUE TITLE
Link to API reference is broken

### ISSUE THREAD

**Issue by mhall0963** [near/near-sdk-js#375]
### Prerequisites

- [X] I'm using the latest version of `near-sdk-js`.
- [ ] I have tried to start with a fresh project and reproduce the defect with minimal code changes.
- [ ] I have read the console error messages carefully (if applicable).

### Description

The link https://docs.near.org/sdk/near-sdk-js from the readme and github description is broken and points to a 404.

### Steps to reproduce

Click https://docs.near.org/sdk/near-sdk-js

### Expected behavior

The reference

### Actual behavior

404

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by gagdiez** [comment]
the correct one is https://near.github.io/near-sdk-js/

@ailisp @thisisjoshford @fospring somebody with access to the settings, please change it

**Comment by thisisjoshford** [comment]
> the correct one is https://near.github.io/near-sdk-js/
> 
> @ailisp @thisisjoshford @fospring somebody with access to the settings, please change it

Fixed :)
