### ISSUE TITLE
Not a function panic using wasm approach

### ISSUE THREAD

**Issue by BenKurrek** [near/near-sdk-js#50]
I've ported over the `standalone` branch into my own JS game (found [here](https://github.com/BenKurrek/near-sdk-js-game)) and I've got it correctly building the `wasm` file. I can deploy the file on-chain but I **cannot** interact with it without getting a `Smart contract panicked: not a function\n` error.

The way I enabled `wasm` support is by simply copying over the `builder.sh` script found in the standalone branch (file found [here](https://github.com/near/near-sdk-js/blob/standalone/builder.sh) in the SDK repo and [here](https://github.com/BenKurrek/near-sdk-js-game/blob/main/builder-wasm.sh) in my game repo). The steps to reproduce is to simply go through the **wasm** version of my README (readme found [here](https://github.com/BenKurrek/near-sdk-js-game#readme)).

This error happens for both view and call functions. An example is shown in the transaction below: [https://explorer.testnet.near.org/transactions/4gieFzFqr8QUsqD7P6rEGSAPsvkHqe9GVvjEBDysakcG](https://explorer.testnet.near.org/transactions/4gieFzFqr8QUsqD7P6rEGSAPsvkHqe9GVvjEBDysakcG)

**Comment by ailisp** [comment]
For your problem: `@nearbindgen` doesn't work with standalone branch. It is quite old, only support low level APIs. See the examples in standalone branch to see what is the contract look like.

Also, note that Standalone branch isn't maintained, it's there for historical reason and reference for other language sdks in future. And the product decision was to not recommend this to users so I don't suggest to try out

**Comment by ailisp** [comment]
We're going to build `@nearbindgen` that works with standalone
