### ISSUE TITLE
Figure out a way to unit test collections

### ISSUE THREAD

**Issue by ailisp** [near/near-sdk-js#51]
quickjs doesn't support require, so cannot conditionally require mocked host functions to test collections

We don’t have to have this before the first release, but certain collections' functionality need at least being tested indirectly by examples

**Comment by ailisp** [comment]
The other attempts I made or thought of:

- Find how to let the js know about whether it is running on nodejs or quickjs. Haven't found a way
- Tried to let the js file directly run in quickjs for test. We'll need to write raw tests since most test framework would not in quickjs environment
- Tried to use require to import different file at runtime. However quickjs doesn't support it.
- Tried to use import as nodejs import syntax, error.
- Tried to use import as function in quickjs, doesn't give error, but it always return empty object
- Tried to mutate a module after import, but it is frozen

Some ways that might work:
- Config babel in a smart way, so that it compiled using mocked host functions for test and resulting module can be tested with quickjs binary
- Modify quickjs.c, add runtime conditional import support
- Modify jsvm.c, make it conditional compiled. For test version, all host functions are mocked

**Comment by volovyk-s** [comment]
If all the above options will fail - we can use workspaces for that.

**Comment by ailisp** [comment]
Yes, workspace is a good approach. We can write contract to test specific APIs
