### ISSUE TITLE
Standalone flag

### ISSUE THREAD

**Issue by gagdiez** [near/near-sdk-js#53]
The current `near-sdk build` command creates a `wasm` file to be deployed in the js-vm. We should give users the option of creating the a standalone wasm file as well.

This could be done adding a `--standalone` flag to `near-sdk build`. In this way `near-sdk build --standalone` would create a `wasm` file ready to deploy in the classic NEAR blockchain.

**Comment by ailisp** [comment]
The challenge is a contract on top of jsvm using some different APIs than standalone, so it's not necessarily a valid standalone contract. We're trying to abstract the API in a uniform way to make this happen

**Comment by gagdiez** [comment]
This issue was created before I had the meeting with the tooling team. Yeah, the standalone and enclave will be separated, so a flag makes no sense in such context. Will close this issue.
