### ISSUE TITLE
Insufficient deposit for storage

### ISSUE THREAD

**Issue by BenKurrek** [near/near-sdk-js#64]
I’m getting a super strange error that I can’t seem to debug… I’m going through and finishing up a gnarly frontend for my game (which is basically finished at this point) and I’m at the point where everything works until you try and make the winning move.

Once you make the winning move, the smart contract panics and says “Smart contract panicked: insufficient deposit for storage”. I’m not adding anything to the state of the contract in this case and I have no clue why it could be throwing this error message… [This](https://github.com/BenKurrek/near-sdk-js-game/blob/f7db65b0e8d6923368741a572c27abad3eea10e4/src/index.js#L67) is a link to what code is being executed in the winning case and [this](https://explorer.testnet.near.org/transactions/F4oNuXwq1ncCS2oVzvtNgLw9FyAdYwxWheDJXa69rxpM) is a link to the transaction.

It looks like the panic is happening within the jsvm contract in the function [deduct_cost](https://github.com/near/near-sdk-js/blob/7a149bf7d8a6bd00cc3c3b7ecc544f96f42bdf8e/jsvm/jsvm.c#L724) which gets executed within a [storage_write](https://github.com/near/near-sdk-js/blob/7a149bf7d8a6bd00cc3c3b7ecc544f96f42bdf8e/jsvm/jsvm.c#L766). I'm confused because the **only thing i'm changing** in this case is that I'm switching a boolean from [true to false](https://github.com/BenKurrek/near-sdk-js-game/blob/f7db65b0e8d6923368741a572c27abad3eea10e4/src/index.js#L69) but the boolean already lives in the state of the contract so this shouldn't take up any excess storage...

**Comment by ailisp** [comment]
I think @volovyk-s 's observation is the right. The `true` is 4 letter and `false` is 5 letter. So you need to deposit a little near to cover additional 1 byte

**Comment by petersalomonsen** [comment]
are there any good way to provide a user experience to be able to call a contract that writes to storage without attaching deposits? e.g. that you could attach the storage deposit in the first call, and then the following calls could be made without the wallet deposit dialog?

**Comment by petersalomonsen** [comment]
or I guess just pad the data written to make sure that the storage has the same length for every call...

**Comment by ailisp** [comment]
> are there any good way to provide a user experience to be able to call a contract that writes to storage without attaching deposits? e.g. that you could attach the storage deposit in the first call, and then the following calls could be made without the wallet deposit dialog?

Should be possible. Currently refund is happen in every call so any user won't have additional deposit left. We can make it to not refund automatically, and add a manual get_my_unused_deposit. The experience will be what you described. Do you think this version is better?

**Comment by petersalomonsen** [comment]
I've been thinking, just to not introduce more complexity, maybe just have the possibility of "padding" as part of writing to storage. So that you can reserve a length when writing to storage. This way you don't need to track deposits per user, and you will still obtain to not refund.

**Comment by ailisp** [comment]
@petersalomonsen good idea, we may let user define the padding and preallocate, predeposit for the padding

**Comment by petersalomonsen** [comment]
is it possible to have the same for also deploying a contract? I notice today that large contracts may be a problem if deploying with a function access key (since it has to be redirected through the wallet in the query string). If you could pre-allocate contract storage then it would be possible to deploy a large contract with a function access key and without redirecting through the wallet.

**Comment by ailisp** [comment]
That's a creative thought! Do you mean for a Rust or standalone JS contract? Seems that a protocol change is required to support that! /cc @AustinBaggio

**Comment by petersalomonsen** [comment]
I mean for JS contract.

Here you can deploy the contract from a web page: https://petersalomonsen.github.io/quickjs-wasm-near/dist/index.html

Normally you are just logged in with a function access key ( not a full access key ), which means that the deployment transaction to the near-js-sdk vm must go via the wallet to sign the transaction for attaching the deposit.

That means also that the contract binary bytes are included in the query string when redirecting to the wallet, but this could be avoided if the contract storage in near-js-sdk vm was pre-allocated.

**Comment by ailisp** [comment]
I see, that makes sense!
