### ISSUE TITLE
`@NearBindgen` is tightly coupled with build tool

### ISSUE THREAD

**Issue by encody** [near/near-sdk-js#68]
I was experimenting with writing an extension for the near-sdk-js library when I discovered [this file](https://github.com/near/near-sdk-js/blob/master/src/build-tools/near-bindgen-exporter.js), which appears to add the code that actually interacts with the JSVM. Unfortunately, this logic is:
- Not particularly easy to read or even find
- Adding functionality to `@NearBindgen` which is not in its definition, i.e. `@NearBindgen` does _more_ than you would believe if you only read [its definition](https://github.com/near/near-sdk-js/blob/master/src/near-bindgen.js#L9-L24)
- Forcing projects to use a particular build tool configuration

I think it would be significantly better for JSVM contracts to simply be ECMAScript modules, where exported functions are the contract's public interface.

**Comment by ailisp** [comment]
The `@NearBindgen` did the same as rust-sdk's `#[near_bindgen]` macro. It is an opinionated design to make two SDKs in a uniform shape.

> I think it would be significantly better for JSVM contracts to simply be ECMAScript modules, where exported functions are the contract's public interface.

This is a feasible alternative, but for every contract's public interface, you'll need to do manual serialization and deserialization the state, taking input from `jsvmInput` and return with `jsvmValueReturn`, which is quite a lot of boilderplate. To get a quick idea on what it's going to look like check this simplified NFT method:

https://github.com/near/near-sdk-js/blob/3a23e5a1c5a33c3f8c6790cccb3a46118993e823/examples/low-level/nft.js

So you still **can choose** to write contract without `@NearBindgen` in above way (we lack some document of doing so, wip), but product side `@NearBindgen` is necessary and give you same abstraction as rust-sdk. We don't want developers to write more lines of JavaScript than Rust to implement equivalent contract :)

**Comment by ryancwalsh** [comment]
> That's fine if the target audience of the JS SDK is Rust smart contract developers.

That would make no sense. The whole point of offering JS is to be more accessible to more people.

> I know that I would prefer to use a JavaScript SDK that feels like it was written by a JavaScript developer, for a JavaScript developer, rather than a JavaScript SDK that feels like it was written by a Rust developer, for a Rust developer.

So yeah, I agree with what @encody is saying in that next line.

@encody I wonder if a 2-min video would help clarify your original point at the top of the issue.  I think @ailisp and I probably aren't understanding the important actionable parts.

**Comment by encody** [comment]
> That would make no sense.

It was half hyperbole. 🤷

I suppose it could make sense if we're trying to transition Rust developers from the Rust SDK to the JS SDK, but I hope we're not doing that.

The primary goal of this issue is to decouple `@NearBindgen` from the build tool. That could mean any combination of the following:
- Moving the functionality currently hidden in `near-bindgen-exporter.js` into the actual definition of `@NearBindgen` if possible
- Using an explicit, rather than implicit, deserialization wrapper/decorator around classes/functions
- Requiring users to manually deserialize state in every function call (not a great solution)
- Passing deserialized state as an additional argument to every function call (also not great)
- Creating a new interface to the contract state that deserializes more easily (maybe moving away from the "default struct" paradigm?)

Video as requested:
https://user-images.githubusercontent.com/7459638/172191426-2b94ab3c-e839-4408-9696-4650a6e01263.mp4

**Comment by ryancwalsh** [comment]
@encody Thanks, that was helpful.

What do you think, @ailisp ? I was surprised to see that you closed this issue already.  I think it's probably worth you and Jacob having a live call (unless you think his followups here were helpful enough).
