### ISSUE TITLE
Warning from use of experimental decorators

### ISSUE THREAD

**Issue by AustinBaggio** [near/near-sdk-js#69]
Experimental decorators might scare of a new to NEAR, or more junior developer. Not sure what the alternatives are to remove or suppress this warning from the SDK so the developer doesn't see it.

(method) StatusMessage.set_greeting(message: any): void Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.ts(1219) No quick fixes available

Using VSCode with JS linter

**Comment by ailisp** [comment]
Unfortunately there is no good way to fix the status of "experimental" because we want a JS SDK, not a TS one, and in JS world decorators are still in "Experimental" stage. We may ship a tsconfig or jsconfig in example project / template projects to remove the warning? cc @volovyk-s

**Comment by volovyk-s** [comment]
I agree that the only way to fix it is to turn it off until this feature is stable.
If it can be done with a config file - let's do it.
