### ISSUE TITLE
Transfer $NEAR in JS contract

### ISSUE THREAD

**Issue by think-in-universe** [near/near-sdk-js#74]
The current near-sdk-js APIs don't support performing actions with [`Promise`](https://docs.rs/near-sdk/4.0.0/near_sdk/struct.Promise.html).

But it's a common requirement that the contract needs to transfer $NEAR from the current contract to another account. (e.g. `new Promise(account_id).transfer(amount)`). Do we plan to support that?

I understand the complexity. because we only have virtual JS contracts in the JSVM, we may need to track the received / sent $NEAR with the virtual JS contract accounts.

A relevant question is to track the [`attached_deposit`](https://docs.rs/near-sdk/4.0.0/near_sdk/env/fn.attached_deposit.html) sent to the JS contract when executing `call_js_contract`.

**Comment by ailisp** [comment]
You're right, the complexity is mostly keep track of how many NEARs stored for each account, as it can only transfer NEAR from jsvm. It shouldn't be very difficult to implement this

**Comment by ailisp** [comment]
@think-in-universe above proposed transfer NEAR in jsvm hasn't been implemented, so this is still an issue. But current standalone sdk (at develop branch) has ability to promise transfer, if you need, check `test_promise_batch_create_transfer` in https://raw.githubusercontent.com/near/near-sdk-js/develop/tests/src/promise_batch_api.js.
