### ISSUE TITLE
Could not load 'examples/hello_near.js'

### ISSUE THREAD

**Issue by BenKurrek** [near/near-sdk-js#8]
I'm currently running on an M1 Max Chip and have installed the prerequisites using the following commands:
1.  `arch -arm64 brew install wget`
2. `arch -arm64 brew install cmake`
3. `arch -arm64 brew install make`

I then ran the setup script followed by the build script:
- `./setup.sh`
- `./build.sh`

Following the instructions for running on testnet, I then ran the following command`./builder.sh examples/hello_near.js` which threw an error saying
```Could not load 'examples/hello_near.js'```

I also tried running `./builder.sh examples/low_level/hello_near.js` but the error was the same.

**Comment by ailisp** [comment]
It looks like your setup and build on M1 is correct given no error shown on `./setup.sh` and `./build.sh`. And the error is maybe on typo in path: `low_level` -> `low-level`?

**Comment by BenKurrek** [comment]
Fixed with https://github.com/near/near-sdk-js/pull/9
