### ISSUE TITLE
`panic` incorrect signature

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-js#80]
Takes a message when there is no message with this host function. Might be misleading for developers

Edit: seems internally this expects a string and then if empty uses the `panic`. A bit of a strange assumption. Feel free to close, but I don't see the benefit in this

**Comment by ailisp** [comment]
My consideration is high level APIs does not need to strictly conform to the low level's host functions. Consider, for example, storage_read. The host function storage_read into register, but rust-sdk & js-sdk version returns the readed bytes.
This polymorphic panic is more likely matched to user's mental model (considering rust's `panic!` and golang's `panic`, both can accept a value or nothing)

**Comment by ailisp** [comment]
> Yes, but this doesn't accept any arbitrary value or nothing, it only expects an empty string or a string

Do you refering to Rust `panic!`? Both js sdk's panic and golang's panic can accept any value or nothing

**Comment by austinabell** [comment]
> > Yes, but this doesn't accept any arbitrary value or nothing, it only expects an empty string or a string
> 
> Do you refering to Rust `panic!`? Both js sdk's panic and golang's panic can accept any value or nothing

It accepts it, but doesn't handle it. Just prints out an error about the undefined value if that's placed in? I can try to repro later, I can't remember the specifics off-hand but you can see that within the jsvm code it handles only empty string and string

**Comment by ailisp** [comment]
I think you are talking this line:

```
static JSValue near_panic(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
  const char *data_ptr;
  size_t data_len;

  if (argc == 1) {
    data_ptr = JS_ToCStringLen(ctx, &data_len, argv[0]);
    panic_utf8(data_len, (uint64_t)data_ptr);
...
```

The C function JS_ToCStringLen works with any JS object, not only strings. If the value `argv[0]` is not a string, `toString()` will be called. The result is always a valid JavaScript String, and its binary representation is a UTF-8 string, can be passed to `panic_utf8`
