### ISSUE TITLE
Allow prefix to be bytes in collections

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-js#84]
There seems to be an implicit bias towards these collections indexing with a string, but this is somewhat limiting because the range of values is somewhat unclear and hard to use if someone wanted to keep prefixes minimal.

Ideally, prefixes and indexing were all done in bytes, so there wasn't a reliance on strings

**Comment by ailisp** [comment]
This string is actually bytes (It can be any `\x00`-`\xff` byte, turns to C `char *`. This has been confusing and document on it isn't obvious: https://github.com/near/near-sdk-js#about-type
