### ISSUE TITLE
Encoded call serialization format

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-js#88]
So the encoding for calls seems to be strings, separated by 0 bytes [https://github.com/near/near-sdk-js/blob/f03eb1a01ee1efbad18a06ab1173edb359e1afdd/src/utils.js#L17](https://github.com/near/near-sdk-js/blob/f03eb1a01ee1efbad18a06ab1173edb359e1afdd/src/utils.js#L17)

But there isn't anything preventing javascript from having a 0 byte in any of these strings (afaik) so someone could just include a zero byte in the string to break the parsing of this. I'm unsure about the implications because I can't seem to easily find where this format is decoded, so if someone could point me in that direction it would be helpful.

To me, a question may be why this format is not versioned to allow things to change in the future. Reasons this could potentially change are:

*   having each serialized bytes length prefixed to avoid ambiguity (mentioned above)
*   Allowing contracts to be called by an index where they are stored – avoiding unnecessary calldata for optimization
*   Switch args serialization from JSON to optimize, or switch the format of this JSON as @volovyk-s is currently exploring

to name a few. Adding a version byte at the start will allow these changes to be handled without hard-breaking existing functionality.

**Comment by ailisp** [comment]
This is actually not a problem. `contract` is AccountId and `method` is a JS identifier, human-readable ascii string. Only `args` is arbitrary bytes that can include `\0` - but `args` is not determined by `\0`, it's determined by length - total host function `input()` length minus the `contract` and `method` part

> so if someone could point me in that direction it would be helpful.

It's in here: https://github.com/near/near-sdk-js/blob/6bb7a0cb83d39639249223a0607816d503f46c9b/jsvm/jsvm.c#L1091

>  so someone could just include a zero byte in the string to break the parsing of this. 

If they're doing so for contract name or method name, the truncated name would be actual name, so wrong contract and wrong method. there isn't security problem but it's wrong logically so they don't have a reason to do that. If they're doing so for args, it's correct behavior - as long as their args is really in correct binary encoding



> having each serialized bytes length prefixed to avoid ambiguity (mentioned above)

So this isn't required

> Allowing contracts to be called by an index where they are stored -- avoiding unnecessary calldata for optimization

This may be need in future, so version can be helpful

> Switch args serialization from JSON to optimize, or switch the format of this JSON as @volovyk-s is currently exploring

Current one can already accept args in non JSON
