### ISSUE TITLE
`near-sdk-js` not working on Windows

### ISSUE THREAD

**Issue by think-in-universe** [near/near-sdk-js#94]
As reported by developers, `near-sdk-js` is not working on Windows, e.g. build contract to base64

![image](https://user-images.githubusercontent.com/46699230/172140746-8fd527b7-16ee-400d-9f71-250b0270b673.png)

We'd better make the "build" command also work well on Windows. 

Testing may still be an issue since sandbox is not working on Windows so far.

**Comment by ailisp** [comment]
The major challenge is we don't have a windows binary of qjsc (quickjs byte code compiler). If you have a windows machine, would you like to help us build one? (On *ix, it's built via `make qjsc`)

**Comment by bucanero** [comment]
> The major challenge is we don't have a windows binary of qjsc (quickjs byte code compiler). If you have a windows machine, would you like to help us build one? (On *ix, it's built via `make qjsc`)

is this still an issue? we could try building a Windows x86/x64 binary using a MinGW environment. 🤔

**Comment by volovyks** [comment]
@bucanero I believe we want SDK to work on Windows natively if it is possible. But we should support WSL as well, not sure if it is possible to test this in CI.

P.S. I have added a test PR to track progress and errors on this issue. We need a volunteer with a Windows machine to work on this.

**Comment by ailisp** [comment]
As we discussed, @volovyks add support via WSL in #295
